import type { Metadata } from 'next'
import "../styles/app.scss"
import StyledComponentsRegistry from '@/lib/antd.registry'
import NextAuthWrapper from '@/lib/next.auth.wrapper'
import { SearchContextProvider } from '@/lib/search.wrapper'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
         <StyledComponentsRegistry>
          <NextAuthWrapper>
            <SearchContextProvider>
            {children}
            </SearchContextProvider>
          </NextAuthWrapper>
         </StyledComponentsRegistry>
      </body>
    </html>
  )
}


